# Generated by Django 3.0.1 on 2020-05-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('player', models.IntegerField()),
                ('victories', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('kills', models.CharField(max_length=100)),
                ('games', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BedWars',
                'verbose_name_plural': 'BedWars',
            },
        ),
        migrations.CreateModel(
            name='donat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
        migrations.CreateModel(
            name='keysi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='MM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('player', models.IntegerField()),
                ('victories', models.IntegerField()),
                ('kills', models.CharField(max_length=100)),
                ('games', models.IntegerField()),
            ],
            options={
                'verbose_name': 'MurderMystery',
                'verbose_name_plural': 'MurderMystery',
            },
        ),
    ]
